// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_STAARpipeline_RCPPEXPORTS_H_GEN_
#define RCPP_STAARpipeline_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace STAARpipeline {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("STAARpipeline", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("STAARpipeline", "_STAARpipeline_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in STAARpipeline");
            }
        }
    }

    inline List matrix_flip_mean(arma::mat G) {
        typedef SEXP(*Ptr_matrix_flip_mean)(SEXP);
        static Ptr_matrix_flip_mean p_matrix_flip_mean = NULL;
        if (p_matrix_flip_mean == NULL) {
            validateSignature("List(*matrix_flip_mean)(arma::mat)");
            p_matrix_flip_mean = (Ptr_matrix_flip_mean)R_GetCCallable("STAARpipeline", "_STAARpipeline_matrix_flip_mean");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_matrix_flip_mean(Shield<SEXP>(Rcpp::wrap(G)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<List >(rcpp_result_gen);
    }

    inline List matrix_flip_minor(arma::mat G) {
        typedef SEXP(*Ptr_matrix_flip_minor)(SEXP);
        static Ptr_matrix_flip_minor p_matrix_flip_minor = NULL;
        if (p_matrix_flip_minor == NULL) {
            validateSignature("List(*matrix_flip_minor)(arma::mat)");
            p_matrix_flip_minor = (Ptr_matrix_flip_minor)R_GetCCallable("STAARpipeline", "_STAARpipeline_matrix_flip_minor");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_matrix_flip_minor(Shield<SEXP>(Rcpp::wrap(G)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<List >(rcpp_result_gen);
    }

}

#endif // RCPP_STAARpipeline_RCPPEXPORTS_H_GEN_
