# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Individual_Score_Test <- function(G, Sigma_i, Sigma_iX, cov, residuals) {
    .Call(`_STAARpipeline_Individual_Score_Test`, G, Sigma_i, Sigma_iX, cov, residuals)
}

Individual_Score_Test_SPA <- function(G, XW, XXWX_inv, residuals, muhat, tol, max_iter) {
    .Call(`_STAARpipeline_Individual_Score_Test_SPA`, G, XW, XXWX_inv, residuals, muhat, tol, max_iter)
}

Individual_Score_Test_cond <- function(G, Sigma_i, Sigma_iX, cov, X_adj, residuals) {
    .Call(`_STAARpipeline_Individual_Score_Test_cond`, G, Sigma_i, Sigma_iX, cov, X_adj, residuals)
}

Individual_Score_Test_cond_multi <- function(G, Sigma_i, Sigma_iX, cov, X_adj, residuals, n_pheno = 1L) {
    .Call(`_STAARpipeline_Individual_Score_Test_cond_multi`, G, Sigma_i, Sigma_iX, cov, X_adj, residuals, n_pheno)
}

Individual_Score_Test_denseGRM <- function(G, P, residuals) {
    .Call(`_STAARpipeline_Individual_Score_Test_denseGRM`, G, P, residuals)
}

Individual_Score_Test_denseGRM_multi <- function(G, P, residuals, n_pheno = 1L) {
    .Call(`_STAARpipeline_Individual_Score_Test_denseGRM_multi`, G, P, residuals, n_pheno)
}

Individual_Score_Test_multi <- function(G, Sigma_i, Sigma_iX, cov, residuals, n_pheno = 1L) {
    .Call(`_STAARpipeline_Individual_Score_Test_multi`, G, Sigma_i, Sigma_iX, cov, residuals, n_pheno)
}

Individual_Score_Test_sp <- function(G, Sigma_i, Sigma_iX, cov, residuals) {
    .Call(`_STAARpipeline_Individual_Score_Test_sp`, G, Sigma_i, Sigma_iX, cov, residuals)
}

Individual_Score_Test_sp_denseGRM <- function(G, P, residuals) {
    .Call(`_STAARpipeline_Individual_Score_Test_sp_denseGRM`, G, P, residuals)
}

Individual_Score_Test_sp_denseGRM_multi <- function(G, P, residuals, n_pheno = 1L) {
    .Call(`_STAARpipeline_Individual_Score_Test_sp_denseGRM_multi`, G, P, residuals, n_pheno)
}

Individual_Score_Test_sp_multi <- function(G, Sigma_i, Sigma_iX, cov, residuals, n_pheno = 1L) {
    .Call(`_STAARpipeline_Individual_Score_Test_sp_multi`, G, Sigma_i, Sigma_iX, cov, residuals, n_pheno)
}

matrix_flip_mean <- function(G) {
    .Call(`_STAARpipeline_matrix_flip_mean`, G)
}

matrix_flip_minor <- function(G) {
    .Call(`_STAARpipeline_matrix_flip_minor`, G)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_STAARpipeline_RcppExport_registerCCallable', PACKAGE = 'STAARpipeline')
})
