# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Individual_Score_Test <- function(G, Sigma_i, Sigma_iX, cov, residuals) {
    .Call(`_STAARpipeline_Individual_Score_Test`, G, Sigma_i, Sigma_iX, cov, residuals)
}

Individual_Score_Test_cond <- function(G, Sigma_i, Sigma_iX, cov, X_adj, residuals) {
    .Call(`_STAARpipeline_Individual_Score_Test_cond`, G, Sigma_i, Sigma_iX, cov, X_adj, residuals)
}

Individual_Score_Test_denseGRM <- function(G, P, residuals) {
    .Call(`_STAARpipeline_Individual_Score_Test_denseGRM`, G, P, residuals)
}

Individual_Score_Test_sp <- function(G, Sigma_i, Sigma_iX, cov, residuals) {
    .Call(`_STAARpipeline_Individual_Score_Test_sp`, G, Sigma_i, Sigma_iX, cov, residuals)
}

Individual_Score_Test_sp_denseGRM <- function(G, P, residuals) {
    .Call(`_STAARpipeline_Individual_Score_Test_sp_denseGRM`, G, P, residuals)
}

matrix_flip_mean <- function(G) {
    .Call(`_STAARpipeline_matrix_flip_mean`, G)
}

matrix_flip_minor <- function(G) {
    .Call(`_STAARpipeline_matrix_flip_minor`, G)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_STAARpipeline_RcppExport_registerCCallable', PACKAGE = 'STAARpipeline')
})
